export enum ActivityStatus {
  NEVER_ATTENDED = 'NEVER_ATTENDED',
  ACTIVE = 'ACTIVE',
  RECENTLY_INACTIVE = 'RECENTLY_INACTIVE',
  INACTIVE = 'INACTIVE',
  LONG_TERM_INACTIVE = 'LONG_TERM_INACTIVE',
}
